// ╔══════════════════════════════════════════════════════════╗
// ║  PACK 1 — VOYAGE                                         ║
// ║  Thèmes : Salutations, Restaurant, Transport, Hôtel,     ║
// ║           Shopping, Santé, Mots-outils, Compteurs        ║
// ╚══════════════════════════════════════════════════════════╝

const THEMES_VOYAGE = [
  { id:'salutations', label:'Salutations',  icon:'🙏', color:'#6b3a6b', pack:'voyage' },
  { id:'restaurant',  label:'Restaurant',   icon:'🍜', color:'#b5342a', pack:'voyage' },
  { id:'transport',   label:'Transport',    icon:'🚃', color:'#1e3a5f', pack:'voyage' },
  { id:'hotel',       label:'Hôtel',        icon:'🏯', color:'#2a7a6e', pack:'voyage' },
  { id:'shopping',    label:'Shopping',     icon:'🛍', color:'#7a4f1e', pack:'voyage' },
  { id:'sante',       label:'Santé',        icon:'🏥', color:'#7a2a2a', pack:'voyage' },
  { id:'grammar',     label:'Mots-outils',  icon:'⟡',  color:'#3d5a3d', pack:'voyage' },
  { id:'compteurs',   label:'Compteurs',    icon:'🔢', color:'#2a4a6e', pack:'voyage' },
];
const CARDS_VOYAGE = [
  // ── SALUTATIONS & POLITESSE (niveau 1)
  { theme:'salutations', level:1, kana:'おはようございます', romaji:'ohayō gozaimasu',  fr:'Bonjour (matin)', kanji:'お早うございます' },
  { theme:'salutations', level:1, kana:'こんにちは',         romaji:'konnichiwa',        fr:'Bonjour (journée)', kanji:'今日は' },
  { theme:'salutations', level:1, kana:'こんばんは',         romaji:'konbanwa',          fr:'Bonsoir', kanji:'今晩は' },
  { theme:'salutations', level:1, kana:'おやすみなさい',     romaji:'oyasumi nasai',     fr:'Bonne nuit', kanji:'お休みなさい' },
  { theme:'salutations', level:1, kana:'さようなら',         romaji:'sayōnara',          fr:'Au revoir (définitif)', kanji:'左様なら' },
  { theme:'salutations', level:1, kana:'またね',             romaji:'mata ne',           fr:'À bientôt / à plus' },
  { theme:'salutations', level:1, kana:'ありがとうございます',romaji:'arigatō gozaimasu', fr:'Merci beaucoup', kanji:'有り難うございます' },
  { theme:'salutations', level:1, kana:'どういたしまして',   romaji:'dō itashimashite',  fr:'De rien / avec plaisir', kanji:'どう致しまして' },
  { theme:'salutations', level:1, kana:'すみません',         romaji:'sumimasen',         fr:'Excusez-moi / pardon', kanji:'済みません' },
  { theme:'salutations', level:1, kana:'ごめんなさい',       romaji:'gomen nasai',       fr:'Je suis désolé(e)', kanji:'御免なさい' },
  { theme:'salutations', level:1, kana:'はい',               romaji:'hai',               fr:'Oui / d\'accord', kanji:'はい' },
  { theme:'salutations', level:1, kana:'いいえ',             romaji:'iie',               fr:'Non' },
  { theme:'salutations', level:1, kana:'わかりました',       romaji:'wakarimashita',     fr:'J\'ai compris / d\'accord', kanji:'分かりました' },
  { theme:'salutations', level:1, kana:'わかりません',       romaji:'wakarimasen',       fr:'Je ne comprends pas', kanji:'分かりません' },
  { theme:'salutations', level:1, kana:'おねがいします',     romaji:'onegaishimasu',     fr:'S\'il vous plaît', kanji:'お願いします' },
  { theme:'salutations', level:1, kana:'いただきます',       romaji:'itadakimasu',       fr:'Bon appétit (avant de manger)', kanji:'頂きます' },
  { theme:'salutations', level:1, kana:'ごちそうさまでした', romaji:'gochisōsama deshita',fr:'Merci pour ce repas', kanji:'御馳走様でした' },
  { theme:'salutations', level:1, kana:'よろしくおねがいします',romaji:'yoroshiku onegaishimasu',fr:'Enchanté(e) / comptez sur moi', kanji:'宜しくお願いします' },
  // niveau 2
  { theme:'salutations', level:2, kana:'はじめまして',             romaji:'hajimemashite',              fr:'Enchanté(e) (première rencontre)', kanji:'初めまして' },
  { theme:'salutations', level:2, kana:'わたしのなまえは〜です',   romaji:'watashi no namae wa ~ desu', fr:'Je m\'appelle ~', kanji:'私の名前は〜です' },
  { theme:'salutations', level:2, kana:'にほんごがすこしはなせます',romaji:'nihongo ga sukoshi hanasemasu',fr:'Je parle un peu japonais', kanji:'日本語が少し話せます' },
  { theme:'salutations', level:2, kana:'えいごがはなせますか',     romaji:'eigo ga hanasemasu ka',      fr:'Parlez-vous anglais ?', kanji:'英語が話せますか' },
  { theme:'salutations', level:2, kana:'もういちどいってください', romaji:'mō ichido itte kudasai',     fr:'Pouvez-vous répéter, s.v.p. ?', kanji:'もう一度言ってください' },
  { theme:'salutations', level:2, kana:'ゆっくりはなしてください', romaji:'yukkuri hanashite kudasai',  fr:'Parlez plus lentement, s.v.p.', kanji:'ゆっくり話してください' },
  { theme:'salutations', level:2, kana:'フランスからきました',     romaji:'Furansu kara kimashita',     fr:'Je viens de France', kanji:'フランスから来ました' },
  { theme:'salutations', level:2, kana:'たのしかったです',         romaji:'tanoshikatta desu',          fr:'C\'était très agréable', kanji:'楽しかったです' },
  { theme:'salutations', level:2, kana:'きをつけて',               romaji:'ki o tsukete',               fr:'Prenez soin de vous / bonne route', kanji:'気をつけて' },

  // ── SALUTATIONS (niveau 3)
  { theme:'salutations', level:3, kana:'おかげさまで',                   romaji:'okage-sama de',                    fr:'Grâce à vous / je vais bien (formule polie)', kanji:'お陰様で' },
  { theme:'salutations', level:3, kana:'おじゃまします',                 romaji:'ojama shimasu',                    fr:'Permettez-moi d\'entrer / je vous dérange', kanji:'お邪魔します' },
  { theme:'salutations', level:3, kana:'ごめんください',                 romaji:'gomen kudasai',                    fr:'Il y a quelqu\'un ? (en entrant)', kanji:'御免ください' },
  { theme:'salutations', level:3, kana:'おせわになっております',         romaji:'osewa ni natte orimasu',           fr:'Merci pour tout ce que vous faites', kanji:'お世話になっております' },
  { theme:'salutations', level:3, kana:'よかったらまたおはなしましょう', romaji:'yokattara mata ohanashi mashō',     fr:'Si vous voulez, parlons encore une fois', kanji:'よかったらまたお話しましょう' },
  { theme:'salutations', level:3, kana:'にほんはいかがですか',           romaji:'nihon wa ikaga desu ka',            fr:'Comment trouvez-vous le Japon ?', kanji:'日本はいかがですか' },
  { theme:'salutations', level:3, kana:'どうぞよろしくおつたえください', romaji:'dōzo yoroshiku otsutae kudasai',   fr:'Transmettez mes amitiés s.v.p.', kanji:'どうぞよろしくお伝えください' },

  // ── RESTAURANT (niveau 1 = mots isolés)
  { theme:'restaurant', level:1, kana:'みず',       romaji:'mizu',         fr:'eau', kanji:'水' },
  { theme:'restaurant', level:1, kana:'おちゃ',     romaji:'ocha',         fr:'thé vert', kanji:'お茶' },
  { theme:'restaurant', level:1, kana:'ビール',     romaji:'bīru',         fr:'bière' },
  { theme:'restaurant', level:1, kana:'さけ',       romaji:'sake',         fr:'saké / alcool de riz', kanji:'酒' },
  { theme:'restaurant', level:1, kana:'ごはん',     romaji:'gohan',        fr:'riz / repas', kanji:'御飯' },
  { theme:'restaurant', level:1, kana:'すし',       romaji:'sushi',        fr:'sushi', kanji:'寿司' },
  { theme:'restaurant', level:1, kana:'ラーメン',   romaji:'rāmen',        fr:'rāmen' },
  { theme:'restaurant', level:1, kana:'てんぷら',   romaji:'tenpura',      fr:'tempura', kanji:'天ぷら' },
  { theme:'restaurant', level:1, kana:'さしみ',     romaji:'sashimi',      fr:'sashimi', kanji:'刺身' },
  { theme:'restaurant', level:1, kana:'めにゅー',   romaji:'menyū',        fr:'menu / carte', kanji:'メニュー' },
  { theme:'restaurant', level:1, kana:'おかんじょう',romaji:'okanjō',       fr:'addition', kanji:'お勘定' },
  { theme:'restaurant', level:1, kana:'からい',     romaji:'karai',        fr:'épicé / piquant', kanji:'辛い' },
  { theme:'restaurant', level:1, kana:'あまい',     romaji:'amai',         fr:'sucré', kanji:'甘い' },
  { theme:'restaurant', level:1, kana:'おいしい',   romaji:'oishii',       fr:'délicieux', kanji:'美味しい' },
  // niveau 2 = phrases courtes
  { theme:'restaurant', level:2, kana:'これをください',      romaji:'kore o kudasai',         fr:'Je voudrais ceci, s\'il vous plaît', kanji:'これを下さい' },
  { theme:'restaurant', level:2, kana:'おすすめはなんですか', romaji:'osusume wa nan desu ka', fr:'Qu\'est-ce que vous recommandez ?', kanji:'お勧めは何ですか' },
  { theme:'restaurant', level:2, kana:'アレルギーがあります', romaji:'arerugī ga arimasu',     fr:'J\'ai une allergie', kanji:'アレルギーがあります' },
  { theme:'restaurant', level:2, kana:'おみずをください',     romaji:'omizu o kudasai',        fr:'De l\'eau, s\'il vous plaît', kanji:'お水を下さい' },
  { theme:'restaurant', level:2, kana:'おかんじょうをください',romaji:'okanjō o kudasai',       fr:'L\'addition, s\'il vous plaît', kanji:'お勘定を下さい' },
  { theme:'restaurant', level:2, kana:'とてもおいしかったです',romaji:'totemo oishikatta desu', fr:'C\'était vraiment délicieux', kanji:'とても美味しかったです' },
  { theme:'restaurant', level:2, kana:'ひとりです',           romaji:'hitori desu',            fr:'Je suis seul(e)', kanji:'一人です' },
  { theme:'restaurant', level:2, kana:'ふたりです',           romaji:'futari desu',            fr:'Nous sommes deux', kanji:'二人です' },

  // ── RESTAURANT (niveau 3)
  { theme:'restaurant', level:3, kana:'このりょうりにはなにがはいっていますか', romaji:'kono ryōri ni wa nani ga haitte imasu ka', fr:'Quels sont les ingrédients de ce plat ?', kanji:'この料理には何が入っていますか' },
  { theme:'restaurant', level:3, kana:'にくなしでつくれますか',         romaji:'niku nashi de tsukuremasu ka',     fr:'Pouvez-vous le faire sans viande ?', kanji:'肉なしで作れますか' },
  { theme:'restaurant', level:3, kana:'おまかせコースをおねがいします', romaji:'omakase kōsu o onegaishimasu',     fr:'Le menu omakase, s.v.p.', kanji:'おまかせコースをお願いします' },
  { theme:'restaurant', level:3, kana:'ざしきせきはありますか',         romaji:'zashiki-seki wa arimasu ka',       fr:'Avez-vous des tables en tatami ?', kanji:'座敷席はありますか' },
  { theme:'restaurant', level:3, kana:'のみほうだいはありますか',       romaji:'nomihōdai wa arimasu ka',          fr:'Avez-vous une formule à volonté à boire ?', kanji:'飲み放題はありますか' },
  { theme:'restaurant', level:3, kana:'きょうのおすすめはなんですか',   romaji:'kyō no osusume wa nan desu ka',    fr:'Quelle est la spécialité du jour ?', kanji:'今日のお勧めは何ですか' },
  { theme:'transport', level:1, kana:'えき',       romaji:'eki',          fr:'gare', kanji:'駅' },
  { theme:'transport', level:1, kana:'でんしゃ',   romaji:'densha',       fr:'train / métro', kanji:'電車' },
  { theme:'transport', level:1, kana:'しんかんせん',romaji:'shinkansen',   fr:'TGV japonais', kanji:'新幹線' },
  { theme:'transport', level:1, kana:'バス',       romaji:'basu',         fr:'bus' },
  { theme:'transport', level:1, kana:'タクシー',   romaji:'takushī',      fr:'taxi' },
  { theme:'transport', level:1, kana:'くうこう',   romaji:'kūkō',         fr:'aéroport', kanji:'空港' },
  { theme:'transport', level:1, kana:'きっぷ',     romaji:'kippu',        fr:'billet / ticket', kanji:'切符' },
  { theme:'transport', level:1, kana:'のりかえ',   romaji:'norikae',      fr:'correspondance', kanji:'乗り換え' },
  { theme:'transport', level:1, kana:'でぐち',     romaji:'deguchi',      fr:'sortie', kanji:'出口' },
  { theme:'transport', level:1, kana:'いりぐち',   romaji:'iriguchi',     fr:'entrée', kanji:'入口' },
  { theme:'transport', level:1, kana:'みぎ',       romaji:'migi',         fr:'droite', kanji:'右' },
  { theme:'transport', level:1, kana:'ひだり',     romaji:'hidari',       fr:'gauche', kanji:'左' },
  { theme:'transport', level:1, kana:'まっすぐ',   romaji:'massugu',      fr:'tout droit', kanji:'真っ直ぐ' },
  { theme:'transport', level:1, kana:'ちかてつ',   romaji:'chikatetsu',   fr:'métro (souterrain)', kanji:'地下鉄' },
  // niveau 2
  { theme:'transport', level:2, kana:'〜はどこですか',            romaji:'~ wa doko desu ka',                fr:'Où se trouve ~ ?', kanji:'〜はどこですか' },
  { theme:'transport', level:2, kana:'〜にいきたいです',           romaji:'~ ni ikitai desu',                 fr:'Je voudrais aller à ~', kanji:'〜に行きたいです' },
  { theme:'transport', level:2, kana:'このでんしゃは〜にとまりますか',romaji:'kono densha wa ~ ni tomarimasu ka',fr:'Ce train s\'arrête-t-il à ~ ?', kanji:'この電車は〜に止まりますか' },
  { theme:'transport', level:2, kana:'きっぷをいちまいください',    romaji:'kippu o ichimai kudasai',          fr:'Un billet, s\'il vous plaît', kanji:'切符を一枚ください' },
  { theme:'transport', level:2, kana:'つぎのえきはどこですか',      romaji:'tsugi no eki wa doko desu ka',     fr:'Où est la prochaine station ?', kanji:'次の駅はどこですか' },
  { theme:'transport', level:2, kana:'なんじにでますか',            romaji:'nanji ni demasu ka',               fr:'À quelle heure part-il ?', kanji:'何時に出ますか' },
  { theme:'transport', level:2, kana:'まよいました',                romaji:'mayoimashita',                     fr:'Je me suis perdu(e)', kanji:'迷いました' },

  // ── TRANSPORT (niveau 3)
  { theme:'transport', level:3, kana:'〜いきのじゅうじかんをおしえてください', romaji:'~ yuki no jūjikan o oshiete kudasai', fr:'Donnez-moi l\'heure de départ pour ~', kanji:'〜行きの出発時間を教えてください' },
  { theme:'transport', level:3, kana:'この〜のかいすうけんはかえますか',  romaji:'kono ~ no kaisūken wa kaemasu ka',  fr:'Puis-je acheter un carnet pour cette ~ ?', kanji:'この〜の回数券は買えますか' },
  { theme:'transport', level:3, kana:'おくれはどのくらいですか',          romaji:'okure wa dono kurai desu ka',       fr:'Quel est le retard approximatif ?', kanji:'遅れはどのくらいですか' },
  { theme:'transport', level:3, kana:'このへんにコインロッカーはありますか',romaji:'kono hen ni koin-rokkā wa arimasu ka',fr:'Y a-t-il des consignes automatiques par ici ?', kanji:'この辺にコインロッカーはありますか' },
  { theme:'transport', level:3, kana:'じゆうせきですか、していせきですか', romaji:'jiyū-seki desu ka, shitei-seki desu ka', fr:'Place libre ou réservée ?', kanji:'自由席ですか、指定席ですか' },

  // ── HÔTEL (niveau 1)
  { theme:'hotel', level:1, kana:'ホテル',       romaji:'hoteru',       fr:'hôtel' },
  { theme:'hotel', level:1, kana:'りょかん',     romaji:'ryokan',       fr:'auberge traditionnelle', kanji:'旅館' },
  { theme:'hotel', level:1, kana:'へや',         romaji:'heya',         fr:'chambre', kanji:'部屋' },
  { theme:'hotel', level:1, kana:'かぎ',         romaji:'kagi',         fr:'clé', kanji:'鍵' },
  { theme:'hotel', level:1, kana:'よやく',       romaji:'yoyaku',       fr:'réservation', kanji:'予約' },
  { theme:'hotel', level:1, kana:'チェックイン', romaji:'chekku-in',    fr:'check-in' },
  { theme:'hotel', level:1, kana:'チェックアウト',romaji:'chekku-auto',  fr:'check-out' },
  { theme:'hotel', level:1, kana:'おふろ',       romaji:'ofuro',        fr:'bain (baignoire)', kanji:'お風呂' },
  { theme:'hotel', level:1, kana:'おんせん',     romaji:'onsen',        fr:'source thermale', kanji:'温泉' },
  { theme:'hotel', level:1, kana:'あさごはん',   romaji:'asagohan',     fr:'petit-déjeuner', kanji:'朝御飯' },
  { theme:'hotel', level:1, kana:'こんばん',     romaji:'konban',       fr:'ce soir', kanji:'今晩' },
  { theme:'hotel', level:1, kana:'いっぱく',     romaji:'ippaku',       fr:'une nuit', kanji:'一泊' },
  // niveau 2
  { theme:'hotel', level:2, kana:'よやくがあります',                  romaji:'yoyaku ga arimasu',                   fr:'J\'ai une réservation', kanji:'予約があります' },
  { theme:'hotel', level:2, kana:'へやをいちまよやくしています',       romaji:'heya o ichima yoyaku shite imasu',     fr:'J\'ai réservé une chambre', kanji:'部屋を一間予約しています' },
  { theme:'hotel', level:2, kana:'チェックインはなんじですか',         romaji:'chekku-in wa nanji desu ka',           fr:'À quelle heure est le check-in ?', kanji:'チェックインは何時ですか' },
  { theme:'hotel', level:2, kana:'インターネットはつかえますか',       romaji:'intānetto wa tsukaemasu ka',           fr:'Puis-je utiliser internet ?', kanji:'インターネットは使えますか' },
  { theme:'hotel', level:2, kana:'おんせんはどこですか',               romaji:'onsen wa doko desu ka',                fr:'Où est le bain thermal ?', kanji:'温泉はどこですか' },
  { theme:'hotel', level:2, kana:'もうひとばんとまれますか',           romaji:'mō hitoban tomaremasu ka',             fr:'Puis-je rester une nuit de plus ?', kanji:'もう一晩泊まれますか' },
  { theme:'hotel', level:2, kana:'まくらをもうひとつください',         romaji:'makura o mō hitotsu kudasai',          fr:'Un oreiller supplémentaire, s.v.p.', kanji:'枕をもう一つください' },

  // ── HÔTEL (niveau 3)
  { theme:'hotel', level:3, kana:'レイトチェックアウトはできますか',     romaji:'reito chekku-auto wa dekimasu ka',  fr:'Le check-out tardif est-il possible ?', kanji:'レイトチェックアウトはできますか' },
  { theme:'hotel', level:3, kana:'にもつをあずかってもらえますか',       romaji:'nimotsu o azukatte moraemasu ka',   fr:'Pouvez-vous garder mes bagages ?', kanji:'荷物を預かってもらえますか' },
  { theme:'hotel', level:3, kana:'このへやからはなみがみえますか',       romaji:'kono heya kara hana-mi ga miemasu ka', fr:'La vue sur les fleurs est-elle visible depuis cette chambre ?', kanji:'この部屋から花見が見えますか' },
  { theme:'hotel', level:3, kana:'ルームサービスをおねがいします',       romaji:'rūmu sābisu o onegaishimasu',       fr:'Je voudrais le room service', kanji:'ルームサービスをお願いします' },
  { theme:'hotel', level:3, kana:'クーラーのつかいかたをおしえてください',romaji:'kūrā no tsukaikata o oshiete kudasai', fr:'Expliquez-moi comment utiliser la climatisation', kanji:'クーラーの使い方を教えてください' },
  { theme:'shopping', level:1, kana:'みせ',       romaji:'mise',         fr:'magasin / boutique', kanji:'店' },
  { theme:'shopping', level:1, kana:'いくら',     romaji:'ikura',        fr:'combien ça coûte ?', kanji:'幾ら' },
  { theme:'shopping', level:1, kana:'やすい',     romaji:'yasui',        fr:'pas cher / bon marché', kanji:'安い' },
  { theme:'shopping', level:1, kana:'たかい',     romaji:'takai',        fr:'cher / élevé', kanji:'高い' },
  { theme:'shopping', level:1, kana:'おみやげ',   romaji:'omiyage',      fr:'souvenir / cadeau', kanji:'お土産' },
  { theme:'shopping', level:1, kana:'ふくろ',     romaji:'fukuro',       fr:'sac', kanji:'袋' },
  { theme:'shopping', level:1, kana:'げんきん',   romaji:'genkin',       fr:'espèces / cash', kanji:'現金' },
  { theme:'shopping', level:1, kana:'クレジットカード',romaji:'kurejitto kādo',fr:'carte de crédit' },
  { theme:'shopping', level:1, kana:'レシート',   romaji:'reshīto',      fr:'reçu' },
  { theme:'shopping', level:1, kana:'へいてん',   romaji:'heiten',       fr:'fermeture', kanji:'閉店' },
  { theme:'shopping', level:1, kana:'かいてん',   romaji:'kaiten',       fr:'ouverture', kanji:'開店' },
  { theme:'shopping', level:1, kana:'ざっか',     romaji:'zakka',        fr:'quincaillerie / bazar', kanji:'雑貨' },
  { theme:'shopping', level:1, kana:'ぜいこみ',   romaji:'zeikomi',      fr:'TTC (taxes incluses)', kanji:'税込み' },
  // niveau 2
  { theme:'shopping', level:2, kana:'これはいくらですか',     romaji:'kore wa ikura desu ka',      fr:'Combien coûte ceci ?', kanji:'これは幾らですか' },
  { theme:'shopping', level:2, kana:'もうすこしやすくなりますか',romaji:'mō sukoshi yasuku narimasu ka',fr:'Pouvez-vous faire un petit geste ?', kanji:'もう少し安くなりますか' },
  { theme:'shopping', level:2, kana:'これをください',          romaji:'kore o kudasai',             fr:'Je prends ceci, s.v.p.', kanji:'これを下さい' },
  { theme:'shopping', level:2, kana:'ちがうサイズはありますか', romaji:'chigau saizu wa arimasu ka', fr:'Avez-vous une autre taille ?', kanji:'違うサイズはありますか' },
  { theme:'shopping', level:2, kana:'みているだけです',         romaji:'mite iru dake desu',         fr:'Je regarde seulement', kanji:'見ているだけです' },
  { theme:'shopping', level:2, kana:'つつんでもらえますか',     romaji:'tsutsunde moraemasu ka',     fr:'Pouvez-vous l\'emballer ?', kanji:'包んでもらえますか' },
  { theme:'shopping', level:2, kana:'カードでしはらえますか',   romaji:'kādo de shiharaemasu ka',    fr:'Puis-je payer par carte ?', kanji:'カードで支払えますか' },

  // ── SHOPPING (niveau 3 = avancé)
  { theme:'shopping', level:3, kana:'めんぜいてんはどこですか',       romaji:'menzei-ten wa doko desu ka',           fr:'Où est la boutique hors-taxes ?', kanji:'免税店はどこですか' },
  { theme:'shopping', level:3, kana:'めんぜいのてつづきをおしえてください', romaji:'menzei no tetsuzuki o oshiete kudasai', fr:'Expliquez-moi la procédure de détaxe', kanji:'免税の手続きを教えてください' },
  { theme:'shopping', level:3, kana:'こちらをはこんでもらえますか',   romaji:'kochira o hakonde moraemasu ka',        fr:'Pouvez-vous me livrer ça ?', kanji:'こちらを運んでもらえますか' },
  { theme:'shopping', level:3, kana:'〜のかいいんカードはありますか', romaji:'~ no kaiin kādo wa arimasu ka',         fr:'Avez-vous une carte fidélité ~ ?', kanji:'〜の会員カードはありますか' },
  { theme:'shopping', level:3, kana:'おかいあげありがとうございます', romaji:'okai-age arigatō gozaimasu',            fr:'Merci de votre achat (formule vendeur)', kanji:'お買い上げありがとうございます' },

  // ── SALUTATIONS (niveau 3)
  { theme:'salutations', level:3, kana:'おかげさまで',                   romaji:'okage-sama de',                    fr:'Grâce à vous / je vais bien (formule polie)' },
  { theme:'salutations', level:3, kana:'おじゃまします',                 romaji:'ojama shimasu',                    fr:'Permettez-moi d\'entrer / je vous dérange' },
  { theme:'salutations', level:3, kana:'ごめんください',                 romaji:'gomen kudasai',                    fr:'Il y a quelqu\'un ? (en entrant)' },
  { theme:'salutations', level:3, kana:'おせわになっております',         romaji:'osewa ni natte orimasu',           fr:'Merci pour tout ce que vous faites' },
  { theme:'salutations', level:3, kana:'よかったらまたおはなしましょう', romaji:'yokattara mata ohanashi mashō',     fr:'Si vous voulez, parlons encore une fois' },
  { theme:'salutations', level:3, kana:'にほんはいかがですか',           romaji:'nihon wa ikaga desu ka',            fr:'Comment trouvez-vous le Japon ?' },
  { theme:'salutations', level:3, kana:'どうぞよろしくおつたえください', romaji:'dōzo yoroshiku otsutae kudasai',   fr:'Transmettez mes amitiés s.v.p.' },

  // ── RESTAURANT (niveau 3)
  { theme:'restaurant', level:3, kana:'このりょうりにはなにがはいっていますか', romaji:'kono ryōri ni wa nani ga haitte imasu ka', fr:'Quels sont les ingrédients de ce plat ?' },
  { theme:'restaurant', level:3, kana:'にくなしでつくれますか',         romaji:'niku nashi de tsukuremasu ka',     fr:'Pouvez-vous le faire sans viande ?' },
  { theme:'restaurant', level:3, kana:'おまかせコースをおねがいします', romaji:'omakase kōsu o onegaishimasu',     fr:'Le menu omakase, s.v.p.' },
  { theme:'restaurant', level:3, kana:'ざしきせきはありますか',         romaji:'zashiki-seki wa arimasu ka',       fr:'Avez-vous des tables en tatami ?' },
  { theme:'restaurant', level:3, kana:'のみほうだいはありますか',       romaji:'nomihōdai wa arimasu ka',          fr:'Avez-vous une formule à volonté à boire ?' },
  { theme:'restaurant', level:3, kana:'きょうのおすすめはなんですか',   romaji:'kyō no osusume wa nan desu ka',    fr:'Quelle est la spécialité du jour ?' },

  // ── TRANSPORT (niveau 3)
  { theme:'transport', level:3, kana:'〜いきのじゅうじかんをおしえてください', romaji:'~ yuki no jūjikan o oshiete kudasai', fr:'Donnez-moi l\'heure de départ pour ~' },
  { theme:'transport', level:3, kana:'この〜のかいすうけんはかえますか',  romaji:'kono ~ no kaisūken wa kaemasu ka',  fr:'Puis-je acheter un carnet pour cette ~ ?' },
  { theme:'transport', level:3, kana:'おくれはどのくらいですか',          romaji:'okure wa dono kurai desu ka',       fr:'Quel est le retard approximatif ?' },
  { theme:'transport', level:3, kana:'このへんにコインロッカーはありますか',romaji:'kono hen ni koin-rokkā wa arimasu ka',fr:'Y a-t-il des consignes automatiques par ici ?' },
  { theme:'transport', level:3, kana:'じゆうせきですか、していせきですか', romaji:'jiyū-seki desu ka, shitei-seki desu ka', fr:'Place libre ou réservée ?' },

  // ── HÔTEL (niveau 3)
  { theme:'hotel', level:3, kana:'レイトチェックアウトはできますか',     romaji:'reito chekku-auto wa dekimasu ka',  fr:'Le check-out tardif est-il possible ?' },
  { theme:'hotel', level:3, kana:'にもつをあずかってもらえますか',       romaji:'nimotsu o azukatte moraemasu ka',   fr:'Pouvez-vous garder mes bagages ?' },
  { theme:'hotel', level:3, kana:'このへやからはなみがみえますか',       romaji:'kono heya kara hana-mi ga miemasu ka', fr:'La vue sur les fleurs est-elle visible depuis cette chambre ?' },
  { theme:'hotel', level:3, kana:'ルームサービスをおねがいします',       romaji:'rūmu sābisu o onegaishimasu',       fr:'Je voudrais le room service' },
  { theme:'hotel', level:3, kana:'クーラーのつかいかたをおしえてください',romaji:'kūrā no tsukaikata o oshiete kudasai', fr:'Expliquez-moi comment utiliser la climatisation' },

  // ── SANTÉ / URGENCES (niveau 1 = mots essentiels)
  { theme:'sante', level:1, kana:'いたい',         romaji:'itai',           fr:'ça fait mal / j\'ai mal', kanji:'痛い' },
  { theme:'sante', level:1, kana:'びょういん',     romaji:'byōin',          fr:'hôpital', kanji:'病院' },
  { theme:'sante', level:1, kana:'くすり',         romaji:'kusuri',         fr:'médicament', kanji:'薬' },
  { theme:'sante', level:1, kana:'きゅうきゅうしゃ',romaji:'kyūkyūsha',      fr:'ambulance', kanji:'救急車' },
  { theme:'sante', level:1, kana:'けいさつ',       romaji:'keisatsu',       fr:'police', kanji:'警察' },
  { theme:'sante', level:1, kana:'たすけて',       romaji:'tasukete',       fr:'Au secours ! / Aidez-moi !', kanji:'助けて' },
  { theme:'sante', level:1, kana:'ねつ',           romaji:'netsu',          fr:'fièvre', kanji:'熱' },
  { theme:'sante', level:1, kana:'ずつう',         romaji:'zutsū',          fr:'mal de tête', kanji:'頭痛' },
  { theme:'sante', level:1, kana:'きぶんがわるい', romaji:'kibun ga warui', fr:'je me sens mal', kanji:'気分が悪い' },
  { theme:'sante', level:1, kana:'アレルギー',     romaji:'arerugī',        fr:'allergie' },
  { theme:'sante', level:1, kana:'きず',           romaji:'kizu',           fr:'blessure / plaie', kanji:'傷' },
  { theme:'sante', level:1, kana:'はきけ',         romaji:'hakike',         fr:'nausée', kanji:'吐き気' },
  { theme:'sante', level:1, kana:'めまい',         romaji:'memai',          fr:'vertige / étourdissement', kanji:'目眩' },
  // niveau 2
  { theme:'sante', level:2, kana:'きゅうきゅうをよんでください',     romaji:'kyūkyū o yonde kudasai',        fr:'Appelez le 119 (urgences), s.v.p.', kanji:'救急を呼んでください' },
  { theme:'sante', level:2, kana:'ちかくのびょういんはどこですか',   romaji:'chikaku no byōin wa doko desu ka', fr:'Où est l\'hôpital le plus proche ?', kanji:'近くの病院はどこですか' },
  { theme:'sante', level:2, kana:'にほんごのわかるいしゃはいますか', romaji:'nihongo no wakaru isha wa imasu ka', fr:'Y a-t-il un médecin parlant anglais/français ?', kanji:'日本語の分かる医者はいますか' },
  { theme:'sante', level:2, kana:'ここがいたいです',                 romaji:'koko ga itai desu',              fr:'J\'ai mal ici', kanji:'ここが痛いです' },
  { theme:'sante', level:2, kana:'このくすりをのんでもいいですか',   romaji:'kono kusuri o nonde mo ii desu ka', fr:'Puis-je prendre ce médicament ?', kanji:'この薬を飲んでもいいですか' },
  { theme:'sante', level:2, kana:'パスポートをなくしました',         romaji:'pasupōto o nakushimashita',      fr:'J\'ai perdu mon passeport', kanji:'パスポートを無くしました' },
  { theme:'sante', level:2, kana:'ほけんしょうはつかえますか',       romaji:'hoken-shō wa tsukaemasu ka',     fr:'Mon assurance est-elle acceptée ?', kanji:'保険証は使えますか' },
  { theme:'sante', level:2, kana:'どろぼうにあいました',             romaji:'dorobō ni aimashita',            fr:'J\'ai été volé(e)', kanji:'泥棒に遭いました' },
  // niveau 3
  { theme:'sante', level:3, kana:'かにアレルギーがあるのでえびもたべられません', romaji:'kani arerugī ga aru no de ebi mo taberaremasen', fr:'J\'ai une allergie aux crabes, donc je ne peux pas manger de crevettes non plus', kanji:'蟹アレルギーがあるので海老も食べられません' },
  { theme:'sante', level:3, kana:'じゅしんひのりょうしゅうしょをいただけますか', romaji:'jūshin-hi no ryōshūsho o itadakemasu ka',        fr:'Puis-je avoir un reçu pour les frais de consultation ?', kanji:'受診費の領収書を頂けますか' },
  { theme:'sante', level:3, kana:'たびほけんのてつづきをしたいのですが',         romaji:'tabi-hoken no tetsuzuki o shitai no desu ga',     fr:'Je souhaite faire une déclaration pour mon assurance voyage', kanji:'旅行保険の手続きをしたいのですが' },
  { theme:'sante', level:3, kana:'ふんしつとどけをだしたいのですが',             romaji:'funshitsu-todoke o dashitai no desu ga',          fr:'Je voudrais déposer une déclaration de perte', kanji:'紛失届を出したいのですが' },
  { theme:'sante', level:3, kana:'にゅういんがひつようですか',                   romaji:'nyūin ga hitsuyō desu ka',                        fr:'Dois-je être hospitalisé(e) ?', kanji:'入院が必要ですか' },

  // ══════════════════════════════════════════════════════
  //  MOTS-OUTILS — adverbes, particules, mots de liaison
  // ══════════════════════════════════════════════════════

  // niveau 1 : particules et adverbes de base
  { theme:'grammar', level:1, kana:'は',         romaji:'wa',          fr:'particule de thème (sujet du discours)' },
  { theme:'grammar', level:1, kana:'が',         romaji:'ga',          fr:'particule de sujet (mise en relief)' },
  { theme:'grammar', level:1, kana:'を',         romaji:'o',           fr:'particule d\'objet direct' },
  { theme:'grammar', level:1, kana:'に',         romaji:'ni',          fr:'particule de lieu / direction / heure' },
  { theme:'grammar', level:1, kana:'で',         romaji:'de',          fr:'particule de lieu d\'action / moyen' },
  { theme:'grammar', level:1, kana:'の',         romaji:'no',          fr:'particule de possession / appartenance' },
  { theme:'grammar', level:1, kana:'と',         romaji:'to',          fr:'et (énumération) / avec (compagnie)' },
  { theme:'grammar', level:1, kana:'も',         romaji:'mo',          fr:'aussi / également' },
  { theme:'grammar', level:1, kana:'か',         romaji:'ka',          fr:'particule interrogative (?)' },
  { theme:'grammar', level:1, kana:'ね',         romaji:'ne',          fr:'n\'est-ce pas ? (recherche d\'accord)' },
  { theme:'grammar', level:1, kana:'よ',         romaji:'yo',          fr:'particule d\'assertion (j\'insiste)' },
  { theme:'grammar', level:1, kana:'へ',         romaji:'e',           fr:'particule de direction (vers)' },
  { theme:'grammar', level:1, kana:'から',       romaji:'kara',        fr:'depuis / à partir de / parce que' },
  { theme:'grammar', level:1, kana:'まで',       romaji:'made',        fr:'jusqu\'à / jusqu\'au moment où' },
  { theme:'grammar', level:1, kana:'でも',       romaji:'demo',        fr:'mais / cependant' },
  { theme:'grammar', level:1, kana:'そして',     romaji:'soshite',     fr:'et puis / ensuite' },
  { theme:'grammar', level:1, kana:'でも',       romaji:'demo',        fr:'mais / pourtant' },
  { theme:'grammar', level:1, kana:'だから',     romaji:'dakara',      fr:'donc / c\'est pourquoi' },

  // niveau 1 : adverbes courants
  { theme:'grammar', level:1, kana:'とても',     romaji:'totemo',      fr:'très / vraiment' },
  { theme:'grammar', level:1, kana:'すこし',     romaji:'sukoshi',     fr:'un peu / légèrement' },
  { theme:'grammar', level:1, kana:'たくさん',   romaji:'takusan',     fr:'beaucoup / en grande quantité' },
  { theme:'grammar', level:1, kana:'もう',       romaji:'mō',          fr:'déjà / encore (selon contexte)' },
  { theme:'grammar', level:1, kana:'まだ',       romaji:'mada',        fr:'encore / pas encore' },
  { theme:'grammar', level:1, kana:'もっと',     romaji:'motto',       fr:'davantage / encore plus' },
  { theme:'grammar', level:1, kana:'いちばん',   romaji:'ichiban',     fr:'le plus / numéro un' },
  { theme:'grammar', level:1, kana:'ぜんぜん',   romaji:'zenzen',      fr:'pas du tout (+ négatif)' },
  { theme:'grammar', level:1, kana:'たぶん',     romaji:'tabun',       fr:'probablement / peut-être' },
  { theme:'grammar', level:1, kana:'きっと',     romaji:'kitto',       fr:'sûrement / sans aucun doute' },
  { theme:'grammar', level:1, kana:'やっぱり',   romaji:'yappari',     fr:'comme je le pensais / comme prévu' },
  { theme:'grammar', level:1, kana:'すぐ',       romaji:'sugu',        fr:'tout de suite / immédiatement' },
  { theme:'grammar', level:1, kana:'ゆっくり',   romaji:'yukkuri',     fr:'lentement / doucement' },
  { theme:'grammar', level:1, kana:'はやく',     romaji:'hayaku',      fr:'vite / tôt' },
  { theme:'grammar', level:1, kana:'いつも',     romaji:'itsumo',      fr:'toujours / d\'habitude' },
  { theme:'grammar', level:1, kana:'ときどき',   romaji:'tokidoki',    fr:'parfois / de temps en temps' },

  // niveau 2 : locutions et connecteurs de phrases
  { theme:'grammar', level:2, kana:'〜てから',       romaji:'~ te kara',         fr:'après avoir fait ~ (séquence)', kanji:'〜てから' },
  { theme:'grammar', level:2, kana:'〜ながら',       romaji:'~ nagara',          fr:'tout en faisant ~ (simultané)', kanji:'〜ながら' },
  { theme:'grammar', level:2, kana:'〜たり〜たりする',romaji:'~ tari ~ tari suru',fr:'faire tantôt ~ tantôt ~ (liste d\'actions)', kanji:'〜たり〜たりする' },
  { theme:'grammar', level:2, kana:'〜と思います',   romaji:'~ to omoimasu',     fr:'je pense que ~ / il me semble que ~', kanji:'〜と思います' },
  { theme:'grammar', level:2, kana:'〜かもしれません',romaji:'~ kamoshiremasen',  fr:'c\'est peut-être ~ / il se peut que ~', kanji:'〜かもしれません' },
  { theme:'grammar', level:2, kana:'〜でしょう',     romaji:'~ deshō',           fr:'ce sera probablement ~ (conjecture polie)', kanji:'〜でしょう' },
  { theme:'grammar', level:2, kana:'〜けど',         romaji:'~ kedo',            fr:'~ mais… / ~ or… (tournure douce)', kanji:'〜けど' },
  { theme:'grammar', level:2, kana:'〜ので',         romaji:'~ no de',           fr:'parce que ~ / comme ~ (cause objective)', kanji:'〜ので' },
  { theme:'grammar', level:2, kana:'〜のに',         romaji:'~ no ni',           fr:'pourtant ~ / bien que ~ (contraste)', kanji:'〜のに' },
  { theme:'grammar', level:2, kana:'〜ばかり',       romaji:'~ bakari',          fr:'rien que ~ / seulement ~ / vient juste de ~', kanji:'〜ばかり' },
  { theme:'grammar', level:2, kana:'〜ほど',         romaji:'~ hodo',            fr:'autant que ~ / à mesure que ~', kanji:'〜ほど' },
  { theme:'grammar', level:2, kana:'なぜなら〜から', romaji:'nazenara ~ kara',   fr:'la raison est que ~ (explication formelle)', kanji:'何故なら〜から' },
  { theme:'grammar', level:2, kana:'それで',         romaji:'sorede',            fr:'alors / c\'est pour ça que', kanji:'それで' },
  { theme:'grammar', level:2, kana:'つまり',         romaji:'tsumari',           fr:'autrement dit / en d\'autres termes', kanji:'つまり' },
  { theme:'grammar', level:2, kana:'たとえば',       romaji:'tatoeba',           fr:'par exemple', kanji:'例えば' },

  // niveau 3 : nuances et registre avancé
  { theme:'grammar', level:3, kana:'〜にもかかわらず',romaji:'~ ni mo kakawarazu', fr:'malgré ~ / en dépit de ~', kanji:'〜にも関わらず' },
  { theme:'grammar', level:3, kana:'〜としては',      romaji:'~ toshite wa',      fr:'en tant que ~ / du point de vue de ~', kanji:'〜としては' },
  { theme:'grammar', level:3, kana:'〜に対して',      romaji:'~ ni taishite',     fr:'envers ~ / par rapport à ~ / en réponse à ~', kanji:'〜に対して' },
  { theme:'grammar', level:3, kana:'〜によると',      romaji:'~ ni yoru to',      fr:'selon ~ / d\'après ~', kanji:'〜によると' },
  { theme:'grammar', level:3, kana:'〜をはじめとして',romaji:'~ o hajime toshite',fr:'~ et notamment / ~ entre autres', kanji:'〜を始めとして' },
  { theme:'grammar', level:3, kana:'〜においては',    romaji:'~ ni oite wa',      fr:'dans le domaine de ~ / en ce qui concerne ~', kanji:'〜においては' },
  { theme:'grammar', level:3, kana:'さらに',          romaji:'sara ni',           fr:'de plus / qui plus est / en outre', kanji:'更に' },
  { theme:'grammar', level:3, kana:'いっぽうで',      romaji:'ippō de',           fr:'d\'un autre côté / en même temps', kanji:'一方で' },

  // ══════════════════════════════════════════════════════
  //  COMPTEURS — nombres, jours, heures
  // ══════════════════════════════════════════════════════

  // niveau 1 : nombres de base
  { theme:'compteurs', level:1, kana:'いち',     romaji:'ichi',    fr:'1' },
  { theme:'compteurs', level:1, kana:'に',       romaji:'ni',      fr:'2' },
  { theme:'compteurs', level:1, kana:'さん',     romaji:'san',     fr:'3' },
  { theme:'compteurs', level:1, kana:'し／よん', romaji:'shi / yon', fr:'4' },
  { theme:'compteurs', level:1, kana:'ご',       romaji:'go',      fr:'5' },
  { theme:'compteurs', level:1, kana:'ろく',     romaji:'roku',    fr:'6' },
  { theme:'compteurs', level:1, kana:'しち／なな',romaji:'shichi / nana', fr:'7' },
  { theme:'compteurs', level:1, kana:'はち',     romaji:'hachi',   fr:'8' },
  { theme:'compteurs', level:1, kana:'きゅう／く',romaji:'kyū / ku', fr:'9' },
  { theme:'compteurs', level:1, kana:'じゅう',   romaji:'jū',      fr:'10' },
  { theme:'compteurs', level:1, kana:'ひゃく',   romaji:'hyaku',   fr:'100' },
  { theme:'compteurs', level:1, kana:'せん',     romaji:'sen',     fr:'1 000' },
  { theme:'compteurs', level:1, kana:'まん',     romaji:'man',     fr:'10 000' },
  { theme:'compteurs', level:1, kana:'じゅうまん',romaji:'jūman',   fr:'100 000' },

  // niveau 1 : jours de la semaine
  { theme:'compteurs', level:1, kana:'にちようび', romaji:'nichi-yōbi', fr:'dimanche' },
  { theme:'compteurs', level:1, kana:'げつようび', romaji:'getsu-yōbi', fr:'lundi' },
  { theme:'compteurs', level:1, kana:'かようび',   romaji:'ka-yōbi',    fr:'mardi' },
  { theme:'compteurs', level:1, kana:'すいようび', romaji:'sui-yōbi',   fr:'mercredi' },
  { theme:'compteurs', level:1, kana:'もくようび', romaji:'moku-yōbi',  fr:'jeudi' },
  { theme:'compteurs', level:1, kana:'きんようび', romaji:'kin-yōbi',   fr:'vendredi' },
  { theme:'compteurs', level:1, kana:'どようび',   romaji:'do-yōbi',    fr:'samedi' },

  // niveau 1 : heures et moments
  { theme:'compteurs', level:1, kana:'〜じ',       romaji:'~ ji',        fr:'~ heure(s) (ex. さんじ = 3h)' },
  { theme:'compteurs', level:1, kana:'〜ふん／ぷん',romaji:'~ fun / pun', fr:'~ minute(s)' },
  { theme:'compteurs', level:1, kana:'ごぜん',     romaji:'gozen',       fr:'matin (AM)' },
  { theme:'compteurs', level:1, kana:'ごご',       romaji:'gogo',        fr:'après-midi (PM)' },
  { theme:'compteurs', level:1, kana:'きょう',     romaji:'kyō',         fr:'aujourd\'hui' },
  { theme:'compteurs', level:1, kana:'きのう',     romaji:'kinō',        fr:'hier' },
  { theme:'compteurs', level:1, kana:'あした',     romaji:'ashita',      fr:'demain' },
  { theme:'compteurs', level:1, kana:'あさ',       romaji:'asa',         fr:'matin' },
  { theme:'compteurs', level:1, kana:'ひる',       romaji:'hiru',        fr:'midi / après-midi' },
  { theme:'compteurs', level:1, kana:'よる',       romaji:'yoru',        fr:'soir / nuit' },

  // niveau 2 : compteurs spéciaux
  { theme:'compteurs', level:2, kana:'〜まい',       romaji:'~ mai',       fr:'compteur de choses plates (billets, feuilles…)', kanji:'〜枚' },
  { theme:'compteurs', level:2, kana:'〜ほん',       romaji:'~ hon',       fr:'compteur de choses longues (bouteilles, stylos…)', kanji:'〜本' },
  { theme:'compteurs', level:2, kana:'〜さつ',       romaji:'~ satsu',     fr:'compteur de livres, cahiers', kanji:'〜冊' },
  { theme:'compteurs', level:2, kana:'〜だい',       romaji:'~ dai',       fr:'compteur de machines, véhicules', kanji:'〜台' },
  { theme:'compteurs', level:2, kana:'〜はい',       romaji:'~ hai',       fr:'compteur de verres, tasses (boissons)', kanji:'〜杯' },
  { theme:'compteurs', level:2, kana:'〜にん',       romaji:'~ nin',       fr:'compteur de personnes (sauf 1 et 2)', kanji:'〜人' },
  { theme:'compteurs', level:2, kana:'ひとり',       romaji:'hitori',      fr:'1 personne', kanji:'一人' },
  { theme:'compteurs', level:2, kana:'ふたり',       romaji:'futari',      fr:'2 personnes', kanji:'二人' },
  { theme:'compteurs', level:2, kana:'〜かい',       romaji:'~ kai',       fr:'étage / fois (occurrence)', kanji:'〜回／〜階' },
  { theme:'compteurs', level:2, kana:'〜かげつ',     romaji:'~ kagetsu',   fr:'~ mois (durée)', kanji:'〜か月' },
  { theme:'compteurs', level:2, kana:'〜ねん',       romaji:'~ nen',       fr:'~ an(s) / année ~', kanji:'〜年' },
  { theme:'compteurs', level:2, kana:'〜にち',       romaji:'~ nichi',     fr:'~ du mois / ~ jour(s)', kanji:'〜日' },
  { theme:'compteurs', level:2, kana:'いつか',       romaji:'itsuka',      fr:'le 5 du mois (irrégulier)', kanji:'五日' },
  { theme:'compteurs', level:2, kana:'とおか',       romaji:'tōka',        fr:'le 10 du mois (irrégulier)', kanji:'十日' },
  { theme:'compteurs', level:2, kana:'はつか',       romaji:'hatsuka',     fr:'le 20 du mois (irrégulier)', kanji:'二十日' },

  // niveau 2 : expressions de temps utiles en voyage
  { theme:'compteurs', level:2, kana:'〜じかん',     romaji:'~ jikan',     fr:'~ heure(s) (durée)', kanji:'〜時間' },
  { theme:'compteurs', level:2, kana:'〜ふつか',     romaji:'~ futsuka',   fr:'2 jours (durée, irrégulier)', kanji:'二日' },
  { theme:'compteurs', level:2, kana:'せんしゅう',   romaji:'senshū',      fr:'la semaine dernière', kanji:'先週' },
  { theme:'compteurs', level:2, kana:'らいしゅう',   romaji:'raishū',      fr:'la semaine prochaine', kanji:'来週' },
  { theme:'compteurs', level:2, kana:'〜じごろ',     romaji:'~ ji goro',   fr:'vers ~ heures (approximatif)', kanji:'〜時頃' },
  { theme:'compteurs', level:2, kana:'〜じはん',     romaji:'~ ji han',    fr:'~ heure et demie', kanji:'〜時半' },

  // niveau 3 : grands nombres, mois, et compteurs rares
  { theme:'compteurs', level:3, kana:'おく',           romaji:'oku',           fr:'100 millions (échelle japonaise)', kanji:'億' },
  { theme:'compteurs', level:3, kana:'いちがつ',       romaji:'ichi-gatsu',    fr:'janvier (1er mois)', kanji:'一月' },
  { theme:'compteurs', level:3, kana:'にがつ',         romaji:'ni-gatsu',      fr:'février', kanji:'二月' },
  { theme:'compteurs', level:3, kana:'さんがつ',       romaji:'san-gatsu',     fr:'mars', kanji:'三月' },
  { theme:'compteurs', level:3, kana:'しがつ',         romaji:'shi-gatsu',     fr:'avril', kanji:'四月' },
  { theme:'compteurs', level:3, kana:'ごがつ',         romaji:'go-gatsu',      fr:'mai', kanji:'五月' },
  { theme:'compteurs', level:3, kana:'ろくがつ',       romaji:'roku-gatsu',    fr:'juin', kanji:'六月' },
  { theme:'compteurs', level:3, kana:'しちがつ',       romaji:'shichi-gatsu',  fr:'juillet', kanji:'七月' },
  { theme:'compteurs', level:3, kana:'はちがつ',       romaji:'hachi-gatsu',   fr:'août', kanji:'八月' },
  { theme:'compteurs', level:3, kana:'くがつ',         romaji:'ku-gatsu',      fr:'septembre', kanji:'九月' },
  { theme:'compteurs', level:3, kana:'じゅうがつ',     romaji:'jū-gatsu',      fr:'octobre', kanji:'十月' },
  { theme:'compteurs', level:3, kana:'じゅういちがつ', romaji:'jūichi-gatsu',  fr:'novembre', kanji:'十一月' },
  { theme:'compteurs', level:3, kana:'じゅうにがつ',   romaji:'jūni-gatsu',    fr:'décembre', kanji:'十二月' },
  { theme:'compteurs', level:3, kana:'〜ひき',         romaji:'~ hiki',        fr:'compteur d\'animaux (petits et moyens)', kanji:'〜匹' },
  { theme:'compteurs', level:3, kana:'〜とう',         romaji:'~ tō',          fr:'compteur de grands animaux', kanji:'〜頭' },
  { theme:'compteurs', level:3, kana:'〜そく',         romaji:'~ soku',        fr:'compteur de paires (chaussures, chaussettes)', kanji:'〜足' },
  { theme:'compteurs', level:3, kana:'〜ちょう',       romaji:'~ chō',         fr:'compteur de choses pliées (vêtements, cartes)', kanji:'〜丁' },
  { theme:'compteurs', level:3, kana:'わごえい',       romaji:'wa・go・ei',    fr:'japonais natif / sino-japonais / emprunts (3 systèmes de comptage)', kanji:'和語・漢語・英語' },
];
